pluginInfo:
  # This is default sample specification
  # Feel free to change it
  pluginName: Sample Glassfish Plugin
  description: Sample plugin to integrate with Glassfish Application Server
  version: 1.0.0
  author: 'Sample Author'
  authorUrl: '<>'
  category: Application Server

# This is a declaration for the plugin configuration
configuration:
  # Shell to be used for checking connection
  shell: ec-perl
  parameters:
   - name: config
     type: entry
     label: Configuration Name
     required: true
     documentation: The name for the created configuration
   - name: cliPath
     label: asadmin CLI Path
     type: entry
     required: true
     documentation: Path to asadmin CLI
     value: asadmin
   - name: credential
     type: credential
     label: Credential
     userNameLabel: Username
     required: true
     passwordLabel: Password

procedures:
- name: Deploy
  description: Deploys an application to Glassfish
  hasConfig: true # configuration field will be generated automatically
  parameters:
  - name: applicationPath
    documentation: Path to the application
    type: entry
    required: true
    label: Application Path
  outputParameters:
    deployed: JSON representation of the deployed application
  # Steps are not defined so we assume that this is one-step procedure with a single step named Deploy
  shell: ec-perl

- name: Undeploy
  description: "Undeploys a previously deployed application"
  hasConfig: true
  parameters:
  - name: applicationName
    documentation: "A name of the deployed application"
    type: entry
    label: Application Name
    required: true
  shell: ec-perl
