pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'SampleAWSCloudFront'
  version: '1.0.0'
  description: 'Example of the plugin that uses AWS CloudFront API'
  author: 'Anton Horodchuk'
  supportUrl: '<>'
  category: 'Utilities'

# Plugin configuration description
configuration:
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
    -
      name: config
      type: entry
      label: Configuration Name
      required: true
      documentation: The name for the created configuration.
    -
      name: desc
      type: entry
      label: Description
      required: false
      documentation: Description for the configuration.
    -
      name: credential
      type: credential
      label: Credential
      userNameLabel: Access key ID
      required: true
      passwordLabel: Secret access key

procedures:
-
  name: 'Invalidate Cache'
  description: 'Invalidates the distribution cache'
  hasConfig: true
  shell: 'ec-groovy'
  parameters:
  -
    name: distributionId
    documentation: The distribution ID associated with the invalidation.
    required: true
    type: entry
    label: Distribution ID
  -
    name: objectPaths
    documentation: Objects paths, newline-separated.
    required: true
    type: textarea
    label: Object Paths
  -
    name: uniqueCallerReference
    documentation: If checked, unique caller reference will be generated automatically.
    required: false
    type: checkbox
    label: Generate Unique Caller Reference
    initiallyChecked: true
    checkedValue: true
    uncheckedValue: false
  -
    name: callerReference
    documentation: Caller reference to identify invalidation request.
    required: false
    type: entry
    label: Caller Reference
    dependsOn: uniqueCallerReference
    condition: ${uniqueCallerReference} == 'false'
  outputParameters:
    invalidationId: Id of the created invalidation