pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'SampleJIRAReporting'
  version: '1.0.0'
  description: 'Sample plugin for a reporting tutorial'
  author: 'Sample Author'
  authorUrl: '<>'
  category: 'Utilities'
# The reporting configuration, will generate a procedure and a bunch of configuration scripts required for DOIS to work
devOpsInsight:
  supportedReports:
    -
      reportObjectType: 'feature'
      parameters:
        -
          name: jiraProjectName
          documentation: A JIRA project that will be used
          required: true
          type: entry
          label: JIRA project name
  # The name of the source as it will appear in the dashboards
  datasourceName: 'JIRA Datasource from tutorial'
  language: 'groovy'

# Plugin configuration description
configuration:
  checkConnection: true
  # This is a declaration for the plugin configuration
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  # parameters:
  restConfigInfo:
    endpointDescription: sample
    endpointLabel: JIRA Server Endpoint
    checkConnectionUri: /rest/api/2/configuration
    headers: {Accept: "application/json"}
    # Auth schemes for the plugin
    authSchemes:
      basic:
        userNameLabel: JIRA User Name
        passwordLabel: JIRA User Password
        description: A username and password to connect to the JIRA instance.
        checkConnectionUri: /rest/api/2/configuration
        credentialLabel: JIRA Credentials
